
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 20 17:21:39 CST 2020
//----------------------------------------------------

package softwarearit.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _const = 56;
  public static final int igualigual = 16;
  public static final int llaveizquierda = 23;
  public static final int imprimir = 3;
  public static final int _return = 50;
  public static final int _do = 42;
  public static final int coma = 22;
  public static final int igual = 17;
  public static final int parentesisizquierda = 27;
  public static final int multiplicacion = 8;
  public static final int _void = 51;
  public static final int diferenteque = 15;
  public static final int mayorque = 12;
  public static final int menosmenos = 5;
  public static final int _typedef = 57;
  public static final int _else = 45;
  public static final int puntoycoma = 21;
  public static final int _enum = 54;
  public static final int corcheteizquierda = 25;
  public static final int masmas = 4;
  public static final int parentesisderecha = 28;
  public static final int menos = 7;
  public static final int _include = 58;
  public static final int EOF = 0;
  public static final int _string = 33;
  public static final int _long = 39;
  public static final int mas = 6;
  public static final int _break = 48;
  public static final int error = 1;
  public static final int _struct = 55;
  public static final int entero = 30;
  public static final int or = 19;
  public static final int menorigual = 13;
  public static final int valorbooleano = 2;
  public static final int punto = 29;
  public static final int _continue = 49;
  public static final int menorque = 11;
  public static final int _if = 43;
  public static final int _id = 32;
  public static final int _while = 46;
  public static final int corchetederecha = 26;
  public static final int _float = 40;
  public static final int _int = 37;
  public static final int _char = 38;
  public static final int _for = 47;
  public static final int mayorigual = 14;
  public static final int _case = 44;
  public static final int and = 18;
  public static final int not = 20;
  public static final int _caracter = 34;
  public static final int _double = 36;
  public static final int umenos = 35;
  public static final int llavederecha = 24;
  public static final int _static = 53;
  public static final int _sizeof = 52;
  public static final int division = 9;
  public static final int modulo = 10;
  public static final int decimal = 31;
  public static final int _short = 41;
}

