
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 25 09:48:18 CST 2020
//----------------------------------------------------

package softwarearit.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _plot = 68;
  public static final int igualigual = 17;
  public static final int _funcion = 46;
  public static final int llaveizquierda = 26;
  public static final int flecha = 20;
  public static final int _return = 45;
  public static final int _array = 51;
  public static final int _mode = 64;
  public static final int _do = 40;
  public static final int coma = 25;
  public static final int igual = 19;
  public static final int _null = 65;
  public static final int _mean = 62;
  public static final int parentesisizquierda = 30;
  public static final int multiplicacion = 9;
  public static final int ternario = 33;
  public static final int string = 5;
  public static final int diferenteque = 18;
  public static final int _switch = 36;
  public static final int mayorque = 14;
  public static final int _ncol = 54;
  public static final int _else = 35;
  public static final int puntoycoma = 24;
  public static final int corcheteizquierda = 28;
  public static final int _list = 49;
  public static final int parentesisderecha = 31;
  public static final int menos = 8;
  public static final int _nrow = 55;
  public static final int EOF = 0;
  public static final int _trunk = 60;
  public static final int mas = 7;
  public static final int _touppercase = 59;
  public static final int _break = 43;
  public static final int error = 1;
  public static final int _barplot = 67;
  public static final int _in = 42;
  public static final int entero = 3;
  public static final int or = 22;
  public static final int menorigual = 15;
  public static final int _length = 53;
  public static final int valorbooleano = 6;
  public static final int _tolowercase = 58;
  public static final int _continue = 44;
  public static final int dospuntos = 32;
  public static final int menorque = 13;
  public static final int _if = 34;
  public static final int potencia = 12;
  public static final int _id = 2;
  public static final int _while = 39;
  public static final int _default = 38;
  public static final int corchetederecha = 29;
  public static final int _pie = 66;
  public static final int _remove = 57;
  public static final int _for = 41;
  public static final int mayorigual = 16;
  public static final int _hist = 69;
  public static final int _case = 37;
  public static final int and = 21;
  public static final int not = 23;
  public static final int _matrix = 50;
  public static final int umenos = 70;
  public static final int _stringlength = 56;
  public static final int llavederecha = 27;
  public static final int _round = 61;
  public static final int _print = 47;
  public static final int _median = 63;
  public static final int division = 10;
  public static final int _c = 48;
  public static final int _typeof = 52;
  public static final int modulo = 11;
  public static final int decimal = 4;
}

